version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:  
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install Angular CLI
          command: |
            cd client
            npm install -g @angular/cli
      - run:
          name: Install client dependencies
          command: |
            cd client
            npm install
      - run:
          name: Run client tests
          command: |
            cd client
            ng test
      - run:
          name: Install server dependencies
          command: |
            cd server
            npm install
      - run:
          name: Run server tests
          command: |
            cd server
            npm test
      - run:
          name: Deploy to production
          command: |
            cd server
            git push heroku master