version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:  
          requires:
            - build
          filters:
            branches:
              only: main
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install global packages
          command: sudo npm install -g @angular/cli
      - run:
          name: Install server dependencies
          command: cd server && npm install
      - run:
          name: Install client dependencies
          command: cd client && npm install

deploy:
  working_directory: ~/repo
  steps:
  - heroku/deploy-via-git