version: 2.1
jobs:
  build:
    working_directory: ~/repo/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: ng test

      - working_directory: ~/repo/server
      - run: npm install
      - run: npm test