version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install client dependencies
          command: |
            cd client
            npm install
      - run:
          name: Run client tests
          command: |
            cd client
            ng test
      - run:
          name: Install server dependencies
          command: |
            cd server
            npm install
      - run:
          name: Run server tests
          command: |
            cd server
            npm test